version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      # Install Terraform
      #- curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
      - sudo yum install -y yum-utils
      - sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - sudo yum install -y terraform
  pre_build:
    commands:
      # Print Terraform version
      - terraform --version

  build:
    commands:
      # Initialize Terraform
      - terraform init

      # Validate Terraform configuration
      - terraform validate

      # Create Terraform plan
      - terraform plan -out=tfplan

# Add post_build phases if needed (e.g., deployment)

artifacts:
  files:
    - tfplan  # Include Terraform plan file as artifact

# Add additional configuration as required
